### ISSUE TITLE
UDF driver

### ISSUE THREAD

**Issue by Zero3K** [jgottula/WinBtrfs#3]
Can you please make one for Windows Server 2003, etc.?

**Comment by jgottula** [comment]
I haven't ever really looked into whether WDM, and UMDF specifically, are suitable for writing filesystem drivers. I know the framework is intended to make writing device drivers easier; and it *may* be possible to write filesystem drivers using UMDF or KMDF, but again, I've never looked into it sufficiently to know for sure.

Regardless, rewriting this project for a different driver framework isn't something you should anticipate me ever doing, for reasons already explained in #2.

If you (or anyone else) want to fork this code and port it to a different framework, feel free to go for it. But again, I'm not interested in developing this project any further, and I haven't been for *literally a decade* (again, as already explained thoroughly in #2).

**Comment by Zero3K** [comment]
Its not UMDF. Its UDF (Universal Disk Format). that I want a driver made which lets the OS read/write from all versions of its specification.
