### ISSUE TITLE
Universal Disk Format driver

### ISSUE THREAD

**Issue by Zero3K** [jgottula/WinBtrfs#4]
Can you please make 32-bit and 64-bit ones for Windows Server 2003, etc.? All revisions of its specification can be found at http://www.osta.org/specs/.

**Comment by Zero3K** [comment]
The Write DVD Now driver that ReactOS uses is broken. Making a new one would be nice for users of it and the official Windows OSes.

**Comment by Zero3K** [comment]
Can you make one or not?

**Comment by Zero3K** [comment]
*bump*

**Comment by jgottula** [comment]
Apologies; but no, sorry.
